### ISSUE TITLE
Date is currently a free text string - can we add stricter validation?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/fireproofbox-standard#1]

**Comment by BibianaC** [comment]
@odscjames  It might be like this:
`
"date_added": {
    "type": "string",
    "format": "date"
}
`

**Comment by odscjames** [comment]
@BibianaC  https://www.jsonschemavalidator.net/ is the web site I was using earlier - if you want to play around and try it?

**Comment by BibianaC** [comment]
@odscjames I have checked it and the validation works well. Something that I have noticed now is that now as required are all items. What happens if just a few of them are required?

**Comment by odscjames** [comment]
Merged.

> Something that I have noticed now is that now as required are all items. What happens if just a few of them are required?

I'm not sure I follow this, sorry?

**Comment by BibianaC** [comment]
@odscjames nothing nothing, I have just realised that there are two required fields.
